# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-31 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(max_length=200)),
                ('test2', models.CharField(max_length=200)),
            ],
        ),
    ]
