# Generated by Django 2.2.10 on 2020-06-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasisInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=50, verbose_name='创建人用户名')),
                ('last_mender', models.CharField(max_length=50, verbose_name='最后修改人用户名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('projectName', models.CharField(default='sdc_dingzhi', max_length=20, verbose_name='母业务')),
                ('appName', models.CharField(default='commissionApp', max_length=20, verbose_name='子业务')),
                ('key', models.CharField(max_length=20, verbose_name='配置名')),
                ('value', models.CharField(max_length=200, verbose_name='配置值')),
            ],
            options={
                'verbose_name': '基础配置信息表',
                'verbose_name_plural': '基础配置信息表',
                'db_table': 'BasisInfo',
            },
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('creator', models.CharField(max_length=50, verbose_name='创建人用户名')),
                ('last_mender', models.CharField(max_length=50, verbose_name='最后修改人用户名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('deviceIp', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='设备ip')),
                ('deviceCatena', models.CharField(default='C', max_length=20, verbose_name='产品系列号')),
                ('sdkName', models.CharField(max_length=20, verbose_name='sdk用户名')),
                ('sdkPass', models.CharField(max_length=20, verbose_name='sdk密码')),
                ('sdkPost', models.CharField(max_length=20, verbose_name='sdk端口号')),
                ('sshName', models.CharField(blank=True, max_length=20, null=True, verbose_name='ssh用户名')),
                ('sshPass', models.CharField(blank=True, max_length=20, null=True, verbose_name='ssh密码')),
                ('sshPost', models.CharField(blank=True, max_length=20, null=True, verbose_name='ssh端口号')),
                ('sftpName', models.CharField(blank=True, max_length=20, null=True, verbose_name='SFTP用户名')),
                ('sftpPass', models.CharField(blank=True, max_length=20, null=True, verbose_name='SFTP密码')),
                ('sftpPost', models.CharField(blank=True, max_length=20, null=True, verbose_name='SFTP端口号')),
                ('sftpPath', models.CharField(blank=True, max_length=200, null=True, verbose_name='sftp绝对路径')),
                ('deviceLogPath', models.CharField(blank=True, max_length=200, null=True, verbose_name='设备日志路径')),
                ('deviceBakLogPath', models.CharField(blank=True, max_length=200, null=True, verbose_name='设备备份日志路径')),
            ],
            options={
                'verbose_name': '设备信息维护表',
                'verbose_name_plural': '设备信息维护表',
                'db_table': 'DeviceInfo',
            },
        ),
        migrations.CreateModel(
            name='LogDownInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=50, verbose_name='创建人用户名')),
                ('last_mender', models.CharField(max_length=50, verbose_name='最后修改人用户名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('deviceIp', models.CharField(max_length=200, verbose_name='设备ip段')),
                ('logSavePath', models.CharField(max_length=200, verbose_name='服务器日志保存路径')),
            ],
            options={
                'verbose_name': '定时下载日志信息表',
                'verbose_name_plural': '定时下载日志信息表',
                'db_table': 'LogDownInfo',
            },
        ),
    ]
