# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-31 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celerys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='test3',
            field=models.CharField(default='', max_length=200),
        ),
    ]
