# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-14 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(db_column='测试', max_length=20)),
                ('name', models.CharField(db_column='轮播图名字', max_length=20)),
            ],
            options={
                'verbose_name': '轮播图表',
                'db_table': 'slideshows',
            },
        ),
    ]
