# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-14 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideshow',
            options={'ordering': ['sort'], 'verbose_name': '轮播图表'},
        ),
        migrations.AddField(
            model_name='slideshow',
            name='img',
            field=models.CharField(max_length=150, null=True, verbose_name='轮播图图片'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='sort',
            field=models.CharField(max_length=20, null=True, verbose_name='图片顺序'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='name',
            field=models.CharField(max_length=20, verbose_name='轮播图名字'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='trackid',
            field=models.CharField(max_length=20, verbose_name='测试'),
        ),
    ]
