# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-14 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0002_auto_20191114_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideshow',
            options={'verbose_name': '轮播图表'},
        ),
        migrations.RemoveField(
            model_name='slideshow',
            name='img',
        ),
        migrations.RemoveField(
            model_name='slideshow',
            name='sort',
        ),
    ]
