# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-14 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0003_auto_20191114_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideshow',
            options={'ordering': ['sort'], 'verbose_name': '轮播图表'},
        ),
        migrations.AddField(
            model_name='slideshow',
            name='img',
            field=models.CharField(max_length=150, null=True, verbose_name='轮播图图片'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='sort',
            field=models.CharField(max_length=20, null=True, verbose_name='图片顺序'),
        ),
    ]
